using UnityEngine;
using Mirror;
using Adrenak.UniVoice;
using Adrenak.UniVoice.Outputs;
using Adrenak.UniVoice.Samples;
using System.Collections;

/// <summary>
/// KISS implementation of Proximity Audio for UniVoice + Mirror.
/// Attach this to the same GameObject as your UniVoiceMirrorSetupSample.
/// </summary>
public class UniVoiceProximityHandler : MonoBehaviour 
{
    [Header("Settings")]
    [SerializeField] float minDistance = 1f;
    [SerializeField] float maxDistance = 30f;

    void Start() {
        StartCoroutine(SetupProximity());
    }

    private IEnumerator SetupProximity() {
        // Wait for UniVoice to be ready
        while (UniVoiceMirrorSetupSample.ClientSession == null) yield return null;
        var session = UniVoiceMirrorSetupSample.ClientSession;

        // 1. Link existing peers (if any)
        foreach (var id in session.PeerOutputs.Keys) {
            StartCoroutine(LinkAudioToPlayer(id));
        }

        // 2. Link future peers as they join
        session.Client.OnPeerJoined += id => {
            StartCoroutine(LinkAudioToPlayer(id));
        };
    }

    private IEnumerator LinkAudioToPlayer(int id) {
        var session = UniVoiceMirrorSetupSample.ClientSession;
        
        // Wait for the PeerOutput to be generated by UniVoice
        while (!session.PeerOutputs.ContainsKey(id)) yield return null;

        // Access the Unity AudioSource (The "Recipe")
        var output = session.PeerOutputs[id] as StreamedAudioSourceOutput;
        if (output == null) {
            Debug.LogError($"[UniVoice Proximity] Output for peer {id} is not a StreamedAudioSourceOutput!");
            yield break;
        }
        var audioSource = output.Stream.UnityAudioSource;

        // Find the corresponding player object in Mirror
        GameObject targetPlayer = null;
        float timeout = 10f; // Don't wait forever

        while (targetPlayer == null && timeout > 0) {
            foreach (var identity in NetworkClient.spawned.Values) {
                // Check in PlayerPhysicsMovement (Jeu) or PlayerObjectController (Lobby)
                if (identity.TryGetComponent(out PlayerPhysicsMovement movement) && movement.ConnectionId == id) {
                    targetPlayer = identity.gameObject;
                    break;
                }
                if (identity.TryGetComponent(out PlayerObjectController controller) && controller.ConnectionId == id) {
                    targetPlayer = identity.gameObject;
                    break;
                }
            }
            if (targetPlayer == null) {
                timeout -= 0.5f;
                yield return new WaitForSeconds(0.5f);
            }
        }

        if (targetPlayer != null) {
            // DO NOT use SetParent! If the player is destroyed (scene change), 
            // the AudioSource would be destroyed too, causing a UniVoice crash.
            // Instead, we just move the output object to the player's position.
            
            audioSource.spatialBlend = 1f; 
            audioSource.rolloffMode = AudioRolloffMode.Linear;
            audioSource.minDistance = minDistance;
            audioSource.maxDistance = maxDistance;

            Debug.Log($"<color=cyan>[UniVoice Proximity]</color> Started following Peer {id} ({targetPlayer.name})");

            while (targetPlayer != null && output != null) {
                output.transform.position = targetPlayer.transform.position + Vector3.up * 1.5f;
                yield return null;
            }

            // If we lose the player, we can reset to 2D or just let it be
            if (output != null) {
                audioSource.spatialBlend = 0f; 
                Debug.Log($"[UniVoice Proximity] Lost player for Peer {id}, resetting to 2D.");
            }
        }
        else {
            Debug.LogWarning($"[UniVoice Proximity] Could not find player object for Peer {id} after 10s. Staying in 2D.");
        }
    }
}
